<a href="https://colab.research.google.com/github/cevikhalil/Data-Science-with-Python-and-Tensorflow/blob/main/17_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np

## Numpy Array

In [67]:
myList = [2,3,4]
np.array(myList)

array([2, 3, 4])

## Arange

In [68]:
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [69]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [70]:
np.arange(0,8,2)

array([0, 2, 4, 6])

## Zeros & Ones

In [71]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [73]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

## Linspace

In [74]:
np.linspace(0,30,6)

array([ 0.,  6., 12., 18., 24., 30.])

In [75]:
np.linspace(0,12,15)

array([ 0.        ,  0.85714286,  1.71428571,  2.57142857,  3.42857143,
        4.28571429,  5.14285714,  6.        ,  6.85714286,  7.71428571,
        8.57142857,  9.42857143, 10.28571429, 11.14285714, 12.        ])

 ## Eye

In [76]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

In [77]:
np.random.randn(4)

array([ 0.15164577, -0.17394512, -0.01497521, -1.06818531])

In [78]:
np.random.randn(3,3)

array([[-0.59330737, -1.40957317, -0.75717951],
       [-1.20885327, -1.13118713, -2.12504966],
       [ 1.20535786, -0.4155362 , -0.97552702]])

In [79]:
np.random.randint(1,88)

46

In [80]:
np.random.randint(1,88,7)

array([14, 26, 36, 24, 55,  8, 34])

## Numpy Array Methods

In [81]:
myArray = np.random.randint(0,40,12)
myArray

array([12, 22, 12, 23, 20,  0, 26, 14, 37, 11,  5,  2])

In [82]:
myArray.reshape(4,3)

array([[12, 22, 12],
       [23, 20,  0],
       [26, 14, 37],
       [11,  5,  2]])

In [83]:
myArray.reshape(2,6)

array([[12, 22, 12, 23, 20,  0],
       [26, 14, 37, 11,  5,  2]])

In [84]:
print("max number: ",myArray.max())
print("index of max: ", myArray.argmax())
print("min number: ",myArray.min())
print("index of min: ", myArray.argmin())

max number:  37
index of max:  8
min number:  0
index of min:  5


In [85]:
myArray.shape

(12,)

## Operations

In [86]:
import numpy as np
myArray = np.arange(0,15)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
myArray[3:5]

array([3, 4])

In [88]:
myArray[3:8] = -3
myArray

array([ 0,  1,  2, -3, -3, -3, -3, -3,  8,  9, 10, 11, 12, 13, 14])

In [89]:
secondArray = np.arange(0,24)
secondArray[4:8]

array([4, 5, 6, 7])

## Matrix

In [90]:
myList = [[10,20,30],[20,30,40],[40,50,60]]
myMatrix = np.array(myList)
myMatrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [91]:
myMatrix[0]

array([10, 20, 30])

In [92]:
myMatrix[1][2]

40

In [94]:
myMatrix[1,2]

40

In [95]:
myMatrix[1:,2]

array([40, 60])

In [96]:
myMatrix[0:,2]

array([30, 40, 60])